use std::{
    env,
    sync::{Arc, Mutex},
};

use tracing::{debug, info, warn};

use crate::{
    devices::{
        errors::{
            CloseError, FindError, InfoError, InitializationError, ListError, OpenError,
            StateError, SubmissionError,
        },
        format::{BufferSize, ChannelSpec, FormatInfo, SampleFormat, SupportedFormat},
        traits::{Device, DeviceProvider, OutputStream},
    },
    media::pipeline::ChannelConsumers,
};

pub type CapturedPlanes = Arc<Mutex<Vec<Vec<f64>>>>;

static CAPTURE: Mutex<Option<CapturedPlanes>> = Mutex::new(None);

/// Install a sink that records every sample reaching the dummy device layer.
/// The bit-transparency tests use this to compare the engine's output against
/// the source samples. Replaces any previously installed sink.
#[cfg_attr(not(test), allow(dead_code))]
pub fn install_capture() -> CapturedPlanes {
    let sink: CapturedPlanes = Arc::new(Mutex::new(Vec::new()));
    *CAPTURE.lock().unwrap() = Some(Arc::clone(&sink));
    sink
}

/// Remove the sink installed by [`install_capture`], if any.
#[cfg_attr(not(test), allow(dead_code))]
pub fn uninstall_capture() {
    *CAPTURE.lock().unwrap() = None;
}

fn capture_samples<T: Copy + Into<f64>>(staging: &[Vec<T>], read: usize) {
    let guard = CAPTURE.lock().unwrap();
    let Some(sink) = guard.as_ref() else { return };

    let mut planes = sink.lock().unwrap();
    if planes.len() < staging.len() {
        planes.resize_with(staging.len(), Vec::new);
    }
    for (plane, channel) in planes.iter_mut().zip(staging) {
        plane.extend(channel[..read].iter().map(|&sample| sample.into()));
    }
}

/// The dummy device provider is provided for testing purposes. It does not play any actual audio,
/// and submitting samples to devices generated by this provider is a no-op.
///
/// This streams provided by this device provider will never block when samples are submitted,
/// meaning that the playback thread will likely submit the next samples immediately.
///
/// The following environment variables can be used to configure the dummy device:
/// - `HB_DUMMY_SAMPLE_RATE`: The sample rate of the dummy device. Defaults to 44100.
/// - `HB_DUMMY_BIT_FORMAT`: The bit format of the dummy device. Defaults to `S16`.
/// - `HB_DUMMY_CHANNELS`: The number of channels of the dummy device. Defaults to 2.
/// - `HB_DUMMY_BUFFER_SIZE`: The buffer size of the dummy device. Defaults to 4096.
///   - This doesn't actually do anything: no samples are ever loaded into a buffer.
pub struct DummyDeviceProvider {}

impl DummyDeviceProvider {
    pub fn new() -> Self {
        Self {}
    }
}

impl DeviceProvider for DummyDeviceProvider {
    fn initialize(&mut self) -> Result<(), InitializationError> {
        info!("DummyDeviceProvider initialized");
        warn!("This device provider WILL not play any actual audio.");
        Ok(())
    }

    fn get_devices(&mut self) -> Result<Vec<Box<dyn Device>>, ListError> {
        debug!("Listing dummy devices");
        Ok(vec![])
    }

    fn get_default_device(&mut self) -> Result<Box<dyn Device>, FindError> {
        debug!("Creating new dummy device");
        Ok(Box::new(DummyDevice {}) as Box<dyn Device>)
    }

    fn get_device_by_uid(&mut self, _: &str) -> Result<Box<dyn Device>, FindError> {
        Err(FindError::DeviceDoesNotExist)
    }
}

pub struct DummyDevice {}

impl DummyDevice {
    pub fn get_sample_rate() -> u32 {
        env::var("HB_DUMMY_SAMPLE_RATE")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(44100)
    }

    pub fn get_bit_format() -> Result<SampleFormat, InfoError> {
        let var = env::var("HB_DUMMY_BIT_FORMAT");
        Ok(match var.as_deref() {
            Ok("F64") => SampleFormat::Float64,
            Ok("F32") => SampleFormat::Float32,
            Ok("S32") => SampleFormat::Signed32,
            Ok("U32") => SampleFormat::Unsigned32,
            Ok("S24") => SampleFormat::Signed24,
            Ok("U24") => SampleFormat::Unsigned24,
            Ok("S16") => SampleFormat::Signed16,
            Ok("U16") => SampleFormat::Unsigned16,
            Ok("S8") => SampleFormat::Signed8,
            Ok("U8") => SampleFormat::Unsigned8,
            Err(std::env::VarError::NotPresent) => SampleFormat::Signed16,
            Ok(_) => Err(InfoError::SampleFmt(var.unwrap()))?,
            Err(std::env::VarError::NotUnicode(os)) => {
                Err(InfoError::SampleFmt(os.to_string_lossy().into_owned()))?
            }
        })
    }

    pub fn get_channels() -> u16 {
        env::var("HB_DUMMY_CHANNELS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(2)
    }

    pub fn get_buffer_size() -> u32 {
        env::var("HB_DUMMY_BUFFER_SIZE")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(4096)
    }
}

impl Device for DummyDevice {
    fn open_device(&mut self, format: FormatInfo) -> Result<Box<dyn OutputStream>, OpenError> {
        let device = DummyStream { format };
        Ok(Box::new(device) as Box<dyn OutputStream>)
    }

    fn get_supported_formats(&self) -> Result<Vec<SupportedFormat>, InfoError> {
        Ok(vec![SupportedFormat {
            originating_provider: "dummy",
            sample_type: DummyDevice::get_bit_format()?,
            sample_rates: (
                DummyDevice::get_sample_rate(),
                DummyDevice::get_sample_rate(),
            ),
            buffer_size: BufferSize::Fixed(DummyDevice::get_buffer_size()),
            channels: ChannelSpec::Count(DummyDevice::get_channels()),
        }])
    }

    fn get_default_format(&self) -> Result<FormatInfo, InfoError> {
        Ok(FormatInfo {
            originating_provider: "dummy",
            sample_type: DummyDevice::get_bit_format()?,
            sample_rate: DummyDevice::get_sample_rate(),
            buffer_size: BufferSize::Fixed(DummyDevice::get_buffer_size()),
            channels: ChannelSpec::Count(DummyDevice::get_channels()),
        })
    }

    fn get_name(&self) -> Result<String, InfoError> {
        Ok("Hummingbird Dummy Audio Device".to_string())
    }

    fn get_uid(&self) -> Result<String, InfoError> {
        Ok("dummy".to_string())
    }

    fn requires_matching_format(&self) -> bool {
        true
    }
}

pub struct DummyStream {
    format: FormatInfo,
}

impl OutputStream for DummyStream {
    fn close_stream(&mut self) -> Result<(), CloseError> {
        debug!("Stream closed.");
        Ok(())
    }

    fn needs_input(&self) -> bool {
        true
    }

    fn play(&mut self) -> Result<(), StateError> {
        debug!("Stream resumed.");
        Ok(())
    }

    fn pause(&mut self) -> Result<(), StateError> {
        debug!("Stream paused.");
        Ok(())
    }

    fn reset(&mut self) -> Result<(), crate::devices::errors::ResetError> {
        debug!("Stream reset.");
        Ok(())
    }

    fn set_volume(&mut self, volume: f64) -> Result<(), StateError> {
        debug!("Volume set to {}.", volume);
        Ok(())
    }

    fn consume_from(
        &mut self,
        input: &mut ChannelConsumers<f64>,
    ) -> Result<usize, SubmissionError> {
        let available = input.potentially_available();
        if available == 0 {
            return Ok(0);
        }

        // Just drain the samples without doing anything with them
        let read = input.try_read_to_staging(available);
        capture_samples(input.staging(), read);
        debug!("Consumed {} samples from ring buffer (dummy device)", read);
        Ok(read)
    }

    fn consume_from_f32(
        &mut self,
        input: &mut ChannelConsumers<f32>,
    ) -> Option<Result<usize, SubmissionError>> {
        if self.format.sample_type != SampleFormat::Float32 {
            return None;
        }

        let available = input.potentially_available();
        if available == 0 {
            return Some(Ok(0));
        }

        let read = input.try_read_to_staging(available);
        capture_samples(input.staging(), read);
        debug!(
            "Consumed {} f32 samples from ring buffer (dummy device)",
            read
        );
        Some(Ok(read))
    }
}
