mod about;
pub mod app;
mod arguments;
mod assets;
pub mod availability;
mod caching;
mod command_palette;
pub mod components;
mod controls;
mod customization;
pub mod data;
mod global_actions;
mod header;
pub mod layout;
pub mod library;
mod lyrics;
pub mod models;
mod queue;
mod scroll_follow;
mod search;
mod settings;
mod shell;
mod side_panel;
pub mod styling;
mod troubleshooting;
pub mod util;
