mod about;
pub mod app;
mod arguments;
mod assets;
pub mod availability;
mod caching;
mod command_palette;
pub mod components;
mod controls;
pub mod data;
mod density;
mod fonts;
mod global_actions;
mod header;
pub mod layout;
pub mod library;
mod lyrics;
pub mod models;
pub(crate) mod presets;
mod queue;
mod right_sidebar;
mod scroll_follow;
mod search;
mod settings;
pub mod styling;
mod troubleshooting;
pub mod util;
