mod about;
pub mod app;
mod arguments;
mod assets;
pub mod availability;
mod caching;
mod command_palette;
pub mod components;
mod controls;
pub mod data;
mod file_options;
mod fonts;
mod global_actions;
mod header;
pub mod layout;
pub mod library;
mod lyrics;
pub mod models;
mod queue;
mod right_sidebar;
mod scale;
mod scroll_follow;
mod search;
mod settings;
mod shell;
pub mod styling;
mod troubleshooting;
mod ui_config;
pub mod util;
