when:
  - event: push
    branch: master

steps:
  - name: build linux amd64 appimage
    image: hummingbird-ci:rust-1.95-bookworm
    pull: false
    environment:
      CARGO_TERM_COLOR: always
      CARGO_TARGET_DIR: /opt/hummingbird/target
      APPIMAGE_EXTRACT_AND_RUN: 1
      LASTFM_API_KEY:
        from_secret: LASTFM_API_KEY
      LASTFM_API_SECRET:
        from_secret: LASTFM_API_SECRET
      MINISIGN_PRIV_KEY:
        from_secret: MINISIGN_PRIV_KEY
      FORGEJO_TOKEN:
        from_secret: FORGEJO_TOKEN
    commands:
      - set +x
      - cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-bundle
      - cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-deploy
      - cargo build --verbose --release -F update
      - cargo cntp-bundle --no-open --verbose
      - cargo cntp-deploy --no-open --verbose --output-file hummingbird-x86_64.AppImage
      - printf '%s' "$MINISIGN_PRIV_KEY" > minisign.key
      - minisign -S -s minisign.key -m hummingbird-x86_64.AppImage
      - ./.woodpecker/scripts/upload-release.sh hummingbird-x86_64.AppImage hummingbird-x86_64.AppImage.minisig
